name: Linux CI


on:
  push:
    branches: [ release/* ]
  pull_request:
    branches: [ release/* ]


jobs:

  build:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: before install
        run: |
          sudo apt-get update
          sudo apt-get install -y yasm
          sudo apt-get install -y libsdl2-dev
          sudo apt-get install -y clang-format
          sudo apt-get install git make gcc autoconf libtool yasm cmake g++ libsdl2-dev
          wget "https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.tar.gz"
          tar zxf cmake-3.16.2-Linux-x86_64.tar.gz
          export PATH=`pwd`/cmake-3.16.2-Linux-x86_64/bin:$PATH
          sudo apt-get install clang llvm
          echo  1 | sudo update-alternatives --config cc

      - name: build_external
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          . setup.env
          cd external/
          ./build_external.sh Linux
          cd ..

      - name: build_cmdline
        run: |
          cd cmdline/
          mkdir build
          cd build
          cmake ../
          make cicadaPlayer

#      - name: before_script_judge
#        if: ${{"$CHECK_FORMAT" == "ON" && "$TRAVIS_PULL_REQUEST" != "false"}}
#        run:
#          curl -L http://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/clang-format-diff.py -o clang-format-diff.py;

#      - name: before_script
#        run: |
#          curl -L http://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/clang-format-diff.py -o clang-format-diff.py;
#          . setup.env
#          cd external/
#          ./build_external.sh Linux
#          cd ../

#      - name: script_judge
#        if: ${{"$CHECK_FORMAT" == "ON"}}
#        run:
#          if: ${{"$TRAVIS_PULL_REQUEST" != "false"}}
#          run:
#            echo "Checking clang-format between TRAVIS_BRANCH=$TRAVIS_BRANCH and TRAVIS_PULL_REQUEST_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH"
#            if: ${{-n $(git diff -U0 --no-color HEAD^ | python ./clang-format-diff.py -p1 -i)}}
#            run: |
#              echo "Run clang-format before submitting a pull request."
#              echo ""
#              git diff -U0 --no-color HEAD^ | python ./clang-format-diff.py -p1 -i
#              exit -1

#      - name: script
#        run: |
#          mkdir build
#          cd build
#          cmake -DCODE_COVERAGE=ON -DTRAVIS=ON -DUSEASAN=ON -DCMAKE_BUILD_TYPE=Debug ../
#          cmake --build . --config Debug -j8
#
#      - name: after_success
#        run: |
#          cd mediaPlayer/tests/
#          ctest -j8 --output-on-failure
#          bash <(curl -s https://codecov.io/bash) -x "llvm-cov gcov" || echo "Codecov did not collect coverage reports"
#          cd ../../framework/tests/
#          ctest -j8 --output-on-failure
#          bash <(curl -s https://codecov.io/bash) -x "llvm-cov gcov" || echo "Codecov did not collect coverage reports"
